{% set name = "model_catalogs" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/model_catalogs-{{ version }}.tar.gz
  sha256: 185cb6f6e49298ff27b680f97ee430b4576742fb922e45566cf6f4eb8a46a9a5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - intake-xarray
    - netcdf4
    - dask-core
    - cf_xarray
    - datetimerange
    - mc-goods
    - numpy
    - siphon
    - pandas
    - intake
    - appdirs
    - requests
    - xarray
    - pip

test:
  imports:
    - model_catalogs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NOAA-ORR-ERD/model_catalogs
  summary: Catalogs for known models
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
    - ChrisBarker-NOAA
